### ISSUE TITLE
Cross-compiling support

### ISSUE THREAD

**Issue by TeroFrondelius** [thelfer/tfel#2] opened 2019-07-12 17:19 UTC
Here is the full output for i686-w64-mingw32: https://travis-ci.org/TeroFrondelius/tfelBuilder/jobs/557939232 and here just the error part:
```bash
[ 36%] Building CXX object mfront/src/CMakeFiles/TFELMFront.dir/MFront.obj
/workspace/srcdir/tfel/mfront/src/MFront.cxx: In member function 'virtual void mfront::MFront::generateDefsFiles()':
/workspace/srcdir/tfel/mfront/src/MFront.cxx:721:30: error: no match for 'operator[]' (operand types are 'mfront::TargetsDescription' and 'const std::basic_string<char>')
       std::copy(this->targets[d].epts.begin(), this->targets[d].epts.end(),
                              ^
/workspace/srcdir/tfel/mfront/src/MFront.cxx:721:61: error: no match for 'operator[]' (operand types are 'mfront::TargetsDescription' and 'const std::basic_string<char>')
       std::copy(this->targets[d].epts.begin(), this->targets[d].epts.end(),
                                                             ^
make[2]: *** [mfront/src/CMakeFiles/TFELMFront.dir/build.make:78: mfront/src/CMakeFiles/TFELMFront.dir/MFront.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:1293: mfront/src/CMakeFiles/TFELMFront.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
ERROR: LoadError: Build for tfel_binaries on i686-w64-mingw32 did not complete successfully
```

Here is the full output for x86_64-unknown-freebsd11.1 https://travis-ci.org/TeroFrondelius/tfelBuilder/jobs/557939233 and here is just the error part:
```bash
[  0%] Building CXX object src/Config/CMakeFiles/TFELConfig.dir/GetInstallPath.o
In file included from /workspace/srcdir/tfel/src/Config/GetInstallPath.cxx:14:
In file included from /opt/x86_64-linux-gnu/tools/../lib/gcc/x86_64-linux-gnu/4.8.5/../../../../x86_64-linux-gnu/include/c++/4.8.5/stdexcept:38:
In file included from /opt/x86_64-linux-gnu/tools/../lib/gcc/x86_64-linux-gnu/4.8.5/../../../../x86_64-linux-gnu/include/c++/4.8.5/exception:37:
In file included from /opt/x86_64-linux-gnu/tools/../lib/gcc/x86_64-linux-gnu/4.8.5/../../../../x86_64-linux-gnu/include/c++/4.8.5/x86_64-linux-gnu/bits/c++config.h:426:
/opt/x86_64-linux-gnu/tools/../lib/gcc/x86_64-linux-gnu/4.8.5/../../../../x86_64-linux-gnu/include/c++/4.8.5/x86_64-linux-gnu/bits/os_defines.h:39:10: fatal error: 'features.h' file not found
#include <features.h>
         ^~~~~~~~~~~~
1 error generated.
make[2]: *** [src/Config/CMakeFiles/TFELConfig.dir/build.make:63: src/Config/CMakeFiles/TFELConfig.dir/GetInstallPath.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:447: src/Config/CMakeFiles/TFELConfig.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
ERROR: LoadError: Build for tfel_binaries on x86_64-unknown-freebsd11.1 did not complete successfully
```

Also 64 bit Windows build fails: https://travis-ci.org/TeroFrondelius/tfelBuilder/jobs/557953091
As well as MacOS: https://travis-ci.org/TeroFrondelius/tfelBuilder/jobs/557976993

**Comment by thelfer** [comment] 2019-07-12 19:29
Hi Tero,
Thanks for reporting this.
Concerning the first issue, it is du to a very recent changes and I indeed misses the Windows case. This will be fixed soon.
Concerning the issue with FreeBSD and MacOS, I can reproduce them and I can compile `TFEL` on both platform without trouble with the default compilers.

**Comment by TeroFrondelius** [comment] 2019-07-15 06:41
> Concerning the issue with FreeBSD and MacOS, I can reproduce them and I can compile `TFEL` on both platform without trouble with the default compilers.

I have tried to debug the build failure and currently, I believe it happens because Cmake somehow finds the wrong include path automatically. In FreeBSD BinaryBuilder.jl uses Clang but in this error message, linux gcc header files are included.

**Comment by TeroFrondelius** [comment] 2019-07-15 09:11
> I indeed misses the Windows case. This will be fixed soon.

I can confirm that the Windows build is working again: https://github.com/TeroFrondelius/tfelBuilder/releases/tag/v0.3.0.

**Comment by TeroFrondelius** [comment] 2019-07-15 09:20
Related to FreeeBSD build issue, @thelfer maybe you can quickly look this `printenv` and tell me if you could see some obvious root cause:
```bash
sandbox:$WORKSPACE/srcdir/tfel# printenv
WINDRES=/opt/x86_64-unknown-freebsd11.1/bin/x86_64-unknown-freebsd11.1-windres
LD_LIBRARY_PATH=/usr/local/lib64:/usr/local/lib:/usr/local/lib:/usr/lib:/lib64:/lib:/opt/x86_64-linux-gnu/lib64:/opt/x86_64-linux-gnu/lib:/opt/x86_64-linux-gnu/x86_64-linux-gnu/lib64:/opt/x86_64-linux-gnu/x86_64-linux-gnu/lib:/opt/x86_64-unknown-freebsd11.1/lib64:/opt/x86_64-unknown-freebsd11.1/lib:/opt/x86_64-unknown-freebsd11.1/x86_64-unknown-freebsd11.1/lib64:/opt/x86_64-unknown-freebsd11.1/x86_64-unknown-freebsd11.1/lib:/workspace/destdir/lib64:/workspace/destdir/lib
LIBTOOL=/opt/x86_64-unknown-freebsd11.1/bin/x86_64-unknown-freebsd11.1-libtool
BUILD_DSYMUTIL=/opt/x86_64-linux-gnu/tools/llvm-dsymutil
LIPO_FOR_BUILD=/opt/x86_64-linux-gnu/bin/x86_64-linux-gnu-lipo
OTOOL=/opt/x86_64-unknown-freebsd11.1/bin/x86_64-unknown-freebsd11.1-otool
prefix=/workspace/destdir
OLDPWD=/workspace/srcdir/tfel
BUILD_AR=/opt/x86_64-linux-gnu/bin/x86_64-linux-gnu-ar
HOSTDSYMUTIL=/opt/x86_64-linux-gnu/tools/llvm-dsymutil
BUILD_AS=/opt/x86_64-linux-gnu/bin/x86_64-linux-gnu-as
AS_FOR_BUILD=/opt/x86_64-linux-gnu/bin/x86_64-linux-gnu-as
LLVM_TARGET=x86_64-unknown-freebsd11.1
HOSTAS=/opt/x86_64-linux-gnu/bin/x86_64-linux-gnu-as
HOSTAR=/opt/x86_64-linux-gnu/bin/x86_64-linux-gnu-ar
CFLAGS=
HOSTRANLIB=/opt/x86_64-linux-gnu/bin/x86_64-linux-gnu-ranlib
FC_FOR_BUILD=/opt/x86_64-linux-gnu/bin/x86_64-linux-gnu-gfortran
HOSTCC=/opt/x86_64-linux-gnu/bin/x86_64-linux-gnu-gcc
OBJCOPY_FOR_BUILD=/opt/x86_64-linux-gnu/bin/x86_64-linux-gnu-objcopy
target=x86_64-unknown-freebsd11.1
CC=/opt/x86_64-linux-gnu/tools/clang -target x86_64-unknown-freebsd11.1 --sysroot /opt/x86_64-unknown-freebsd11.1/x86_64-unknown-freebsd11.1/sys-root
READELF=/opt/x86_64-unknown-freebsd11.1/bin/x86_64-unknown-freebsd11.1-readelf
PKG_CONFIG_SYSROOT_DIR=/workspace/destdir
BUILD_READELF=/opt/x86_64-linux-gnu/bin/x86_64-linux-gnu-readelf
STRIP=/opt/x86_64-unknown-freebsd11.1/bin/x86_64-unknown-freebsd11.1-strip
OBJCOPY=/opt/x86_64-unknown-freebsd11.1/bin/x86_64-unknown-freebsd11.1-objcopy
BUILD_CXX=/opt/x86_64-linux-gnu/bin/x86_64-linux-gnu-g++
NM_FOR_BUILD=/opt/x86_64-linux-gnu/bin/x86_64-linux-gnu-nm
WINMC=/opt/x86_64-unknown-freebsd11.1/bin/x86_64-unknown-freebsd11.1-winmc
LIPO=/opt/x86_64-unknown-freebsd11.1/bin/x86_64-unknown-freebsd11.1-lipo
WORKSPACE=/workspace
HOSTLD=/opt/x86_64-linux-gnu/bin/x86_64-linux-gnu-ld
PWD=/workspace/srcdir/tfel
HOSTOBJCOPY=/opt/x86_64-linux-gnu/bin/x86_64-linux-gnu-objcopy
dlext=so
RANLIB=/opt/x86_64-unknown-freebsd11.1/bin/x86_64-unknown-freebsd11.1-ranlib
OBJDUMP=/opt/x86_64-linux-gnu/tools/llvm-objdump
DSYMUTIL=/opt/x86_64-linux-gnu/tools/llvm-dsymutil
HISTFILE=/meta/.bash_history
AS=/opt/x86_64-linux-gnu/tools/llvm-as
AR=/opt/x86_64-linux-gnu/tools/llvm-ar
CC_FOR_BUILD=/opt/x86_64-linux-gnu/bin/x86_64-linux-gnu-gcc
BUILD_OBJDUMP=/opt/x86_64-linux-gnu/bin/x86_64-linux-gnu-objdump
RANLIB_FOR_BUILD=/opt/x86_64-linux-gnu/bin/x86_64-linux-gnu-ranlib
HOSTFC=/opt/x86_64-linux-gnu/bin/x86_64-linux-gnu-gfortran
FC=/opt/x86_64-unknown-freebsd11.1/bin/x86_64-unknown-freebsd11.1-gfortran
OBJDUMP_FOR_BUILD=/opt/x86_64-linux-gnu/bin/x86_64-linux-gnu-objdump
LLVM_HOST_TARGET=x86_64-linux-gnu
DSYMUTIL_FOR_BUILD=/opt/x86_64-linux-gnu/tools/llvm-dsymutil
nproc=4
NM=/opt/x86_64-linux-gnu/tools/llvm-nm
CXX=/opt/x86_64-linux-gnu/tools/clang++ -target x86_64-unknown-freebsd11.1 --sysroot /opt/x86_64-unknown-freebsd11.1/x86_64-unknown-freebsd11.1/sys-root
proc_family=intel
TERM=screen
INSTALL_NAME_TOOL=/opt/x86_64-unknown-freebsd11.1/bin/x86_64-unknown-freebsd11.1-install_name_tool
BUILD_NM=/opt/x86_64-linux-gnu/bin/x86_64-linux-gnu-nm
HOSTNM=/opt/x86_64-linux-gnu/bin/x86_64-linux-gnu-nm
SHLVL=1
BUILD_LD=/opt/x86_64-linux-gnu/bin/x86_64-linux-gnu-ld
HOSTSTRIP=/opt/x86_64-linux-gnu/bin/x86_64-linux-gnu-strip
CPPFLAGS=
READELF_FOR_BUILD=/opt/x86_64-linux-gnu/bin/x86_64-linux-gnu-readelf
BUILD_FC=/opt/x86_64-linux-gnu/bin/x86_64-linux-gnu-gfortran
BUILD_LIPO=/opt/x86_64-linux-gnu/bin/x86_64-linux-gnu-lipo
LDFLAGS= -L/opt/x86_64-unknown-freebsd11.1/x86_64-unknown-freebsd11.1/lib
STRIP_FOR_BUILD=/opt/x86_64-linux-gnu/bin/x86_64-linux-gnu-strip
HOSTOBJDUMP=/opt/x86_64-linux-gnu/bin/x86_64-linux-gnu-objdump
nbits=64
CXX_FOR_BUILD=/opt/x86_64-linux-gnu/bin/x86_64-linux-gnu-g++
LD_FOR_BUILD=/opt/x86_64-linux-gnu/bin/x86_64-linux-gnu-ld
PATH=/opt/x86_64-unknown-freebsd11.1/bin:/opt/x86_64-linux-gnu/bin:/opt/x86_64-linux-gnu/tools:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/workspace/destdir/bin
BUILD_OBJCOPY=/opt/x86_64-linux-gnu/bin/x86_64-linux-gnu-objcopy
PS1=sandbox:${PWD//$WORKSPACE/\\$WORKSPACE}\$ 
BUILD_CC=/opt/x86_64-linux-gnu/bin/x86_64-linux-gnu-gcc
BUILD_RANLIB=/opt/x86_64-linux-gnu/bin/x86_64-linux-gnu-ranlib
PKG_CONFIG_PATH=/workspace/destdir/lib/pkgconfig
HOSTCXX=/opt/x86_64-linux-gnu/bin/x86_64-linux-gnu-g++
BUILD_STRIP=/opt/x86_64-linux-gnu/bin/x86_64-linux-gnu-strip
LD=/opt/x86_64-linux-gnu/tools/llvm-ld
AR_FOR_BUILD=/opt/x86_64-linux-gnu/bin/x86_64-linux-gnu-ar
HOSTLIPO=/opt/x86_64-linux-gnu/bin/x86_64-linux-gnu-lipo
HOSTREADELF=/opt/x86_64-linux-gnu/bin/x86_64-linux-gnu-readelf
_=/bin/printenv
sandbox:$WORKSPACE/srcdir/tfel# 
```

**Comment by thelfer** [comment] 2019-12-13 09:37
Hi @TeroFrondelius,
Closing the issue as I can't reproduce it on any of the virtual machine...

**Closed by thelfer** 2019-12-13 09:37 UTC
